name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i --verbose src/chessviz/main.c src/libchessviz/check_move.c src/libchessviz/check_move.h src/libchessviz/check_read_move.c src/libchessviz/check_read_move.h src/libchessviz/move.c src/libchessviz/move.h src/libchessviz/print_field.c src/libchessviz/print_field.h src/read_move.c src/libchessviz/read_move.h && git diff --exit-code

      - name: Build application
        run: make

      - name: Test application
        run: make Test

      - name: Run Test
        run: ./bin/chessviz-test
